version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
cache: c:\vcpkg\ -> appveyor.yml
install:
  - cmd: >-
      cd c:\
      
      IF NOT EXIST c:\vcpkg\ ( git clone https://github.com/Microsoft/vcpkg ) ELSE ( echo VCPKG is cached )
      
      cd vcpkg
      
      powershell -exec bypass scripts\bootstrap.ps1
      
      .\vcpkg integrate install
      
      .\vcpkg install opencv
      
      cd c:\projects\mruby-webcam
      
  - cinst winflexbison
init:
- call "%visualcpp%" %machine%
- set YACC=win_bison
build_script:
 - cd ..
 - git clone https://github.com/mruby/mruby.git
 - cd mruby
 - set MRUBY_CONFIG=..\mruby-webcam\appveyor_config.rb
 - rake all test
