version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
install:
  - cinst winflexbison
  - cinst opencv
  - dir C:\tools\opencv\build\include
  - dir C:\tools\opencv\build\x64
init:
  - call "%visualcpp%" %machine%
  - echo %machine%
  - set YACC=win_bison
  #- set INCLUDE=C:\vcpkg\installed\x64-windows\include;%INCLUDE%
  #- set LIB=C:\vcpkg\installed\x64-windows\lib;%LIB%
  #- set PATH=C:\vcpkg\installed\x64-windows\bin;%PATH%
build_script:
 - cd ..
 #- git clone https://github.com/mruby/mruby.git
 #- cd mruby
 #- set MRUBY_CONFIG=..\mruby-webcam\appveyor_config.rb
 #- rake all test
