version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
install:
  - cinst winflexbison
init:
- call "%visualcpp%" %machine%
- set YACC=win_bison
build_script:
 - cd ..
 - git clone https://github.com/mruby/mruby.git
 - cd mruby
 - set MRUBY_CONFIG=..\mruby-webcam\appveyor_config.rb
 - rake all test
